### ISSUE TITLE
Add commands for setting map layers

### ISSUE THREAD

**Issue by timraay** [timraay/Archon#14]
As of Squad V2 two new admin commands were added to set the current or upcoming layer, `AdminChangeLayer` and `AdminSetNextLayer`. This works similar to setting the map, but takes a layer as argument instead of a map. A bot command needs to be implemented to execute this command over RCON.

First, register the server command here.
https://github.com/timraay/Archon/blob/fa83f289898807ff82ef6f740c159baf56404472/rcon/commands.py#L107-L118

Then, add the bot command and user interface to set the next layer, just like the command for setting the next map. You can get rid of `inst.next_map = map_name`. Make sure to add the `@is_game` wrapper as well, to make sure this command only works for Squad servers:
https://github.com/timraay/Archon/blob/fa83f289898807ff82ef6f740c159baf56404472/cogs/moderation.py#L237-L246

**Comment by Striver08** [comment]
I'm new to Open Source and found this project, can you please tell me about this issue.

**Comment by timraay** [comment]
I've edited the issue description. If you want to know anything else feel free to ask.
