### ISSUE TITLE
Unable to connect to the server: Unknown host

### ISSUE THREAD

**Issue by RamboKilo** [timraay/Archon#28]
The bot is not recognizing servers anymore can we possibly get an update/look into this thanks very much.

Archon
BOT
 — Today at 16:02
Trying to establish a connection...
Unable to connect to the server: Unknown host

**Comment by RamboKilo** [comment]
Looks like its fixed now thanks if it was acted upon

**Comment by timraay** [comment]
I've not changed anything. Was most likely a misconfiguration or firewall issue on your end.
